### ISSUE TITLE
Audience advisory info for write-ups

### ISSUE THREAD

**Issue by matr1x-hackmud** [comcode-org/hackmud_wiki#56]
### Problem

When creating write-ups for game content, articles will be varied in the audience they're intended to target. We don't players who are still in the early game to wander into articles like "how to crack the gibson" or other endgame content that they may not want spoiled.

### Suggestions

We could create an advisory template to include on the top of relevant articles identifying what stage of gameplay the write-up/article pertains to ("Tutorial/vLAN", "Earlygame"/T1, &c) which would allow more granular understanding of what a spoilery article is going to touch on

**Comment by seanmakesgames** [comment]
Reading through the issue description here, it seems like the actual problem is that:

"We don't want players who are still in the early game to wander into articles like "how to crack the gibson" or other endgame content that they may not want spoiled."

It is too early in the development and test process of the wiki to know if this is actually a problem we will need to solve, so at this point, we will close the issue as wontfix until we have evidence that this is impacting players.
