### ISSUE TITLE
CommonJS module syntax ("require") vs. ECMAScript modules ("import")

### ISSUE THREAD

**Issue by ast-ral** [comcode-org/hackmud_wiki#9]
# Brief Overview

* Node.js has 2 supported syntaxes for importing dependencies: the [CommonJS](https://nodejs.org/api/modules.html) syntax (`const {item_a, item_b} = require("./file.js");`) and the [ECMAScript](https://nodejs.org/api/esm.html) syntax (`import {item_a, item_b} from "./file.js";`).
* For historical reasons, Node.js defaults to the CommonJS syntax (it existed before the ECMAScript syntax did).
* CommonJS modules are imported synchronously, whereas ECMAScript modules are imported asynchronously.
* You can import a CommonJS module from inside an ECMAScript module without issue.
* You can import an ECMAScript module from a CommonJS module only as a Promise which eventually resolves to the exports of the ECMAScript module. This means that any function in a CommonJS module relying on functionality from an ECMAScript module _must_ be marked asynchronous (so that it can await the dependency). Importing ECMAScript from ECMAScript does not have this problem.
* CommonJS does _not_ support top-level awaits, but ECMAScript modules do.
* If you need to explicitly disambiguate how a `.js` file should be interpreted, rename to `.cjs` for CommonJS, and `.mjs` for ECMAScript modules.

Please ask if you have questions, I've presented a very watered-down background here so that people unfamiliar with the distinction have at least a vague idea of what's going on.

# The Problem

The plugin system that Docusaurus supports is based on [remark](https://github.com/remarkjs/remark) and [rehype](https://github.com/rehypejs/rehype). These are part of the [unifiedjs](https://unifiedjs.com/) umbrella, a group of software packages for manipulating AST-like data. It would make sense to use plugins from within this ecosystem in order to manipulate the ASTs that we receive inside remark and rehype plugins, however, many dependencies in this space *only* support being imported as an ECMAScript module. [hast-util-find-and-replace](https://github.com/syntax-tree/hast-util-find-and-replace) serves as a good example.

On the other hand, Docusaurus *only* supports the config file (by default, `docusaurus.config.js`) being a CommonJS module, not an ECMAScript one. This is not a dealbreaker, because Docusaurus supports setting `module.exports = async function () {/* returns config object */};` instead of directly doing `module.exports = /* config object */;`. We could import an ECMAScript module using `await import("./path/to/ecmascript/module.js")` directly within this function, or we could await another function from a CommonJS module which then imports an ECMAScript module, for example. Essentially, somewhere in the require/import tree, we're going to have to have a CommonJS module importing an ECMAScript module, and it would be good to have a plan for where exactly this is going to occur.

# Proposed Solution

My preferred solution is that all source files are marked as ECMAScript modules by default (by setting `"type": "module"` in `./package.json`), and that we have a single CommonJS shim `docusaurus.config.shim.cjs` that uses `await import` to import the _real_ config file `docusaurus.config.js` (which would now be an ECMAScript module, along with everything else but the shim). `docusaurus.config.js` can now import ECMAScript modules without worry, as ECMAScript import from ECMAScript is seamless. This will also require modifying `package.json` so that the Docusaurus commands have `--config ./docusaurus.config.shim.cjs` to retarget the config file from the default name. This solution corresponds to the transition from CommonJS to ECMAScript modules happening immediately and only once: there is only 1 very short CommonJS module which imports an ECMAScript module, and everything else is ECMAScript.

The benefit of doing this is:
1. With a singular exception, we establish a consistent style of writing only one kind of module.
2. We only have to do the hack of `await import`-ing an ECMAScript module from a CommonJS module once. We would have to do this every time we wanted to import an ECMAScript module from a CommonJS module otherwise.
3. ECMAScript modules are the official way of writing JavaScript modules (according to the organization that standardizes the language).

# Bikeshed

* `docusaurus.config.shim.cjs` could probably have a better name, or we could keep the shim as the default name (`docusaurus.config.cjs`), which then imports `docusaurus.config.ecmascript.js` which imports everything else or similar.

# Alternatives

In my opinion, the only reasonable alternative is writing only CommonJS modules, as mixing module types within our repository would be confusing at best. This alternative has the aforementioned downside that any time we want to import an ECMAScript-only dependency, we will have to mark any functions which rely on the ECMAScript module's exports as `async function` and do something like `const {item_a, item_b} = await import("ecmascript_module");` within that function to receive the ECMAScript module's exports.

We could also try to find other dependencies for manipulating HTML/Markdown ASTs that _do_ allow import as CommonJS modules, however, I don't know of any.

**Comment by danswann** [comment]
> The plugin system that Docusaurus supports is based on [remark](https://github.com/remarkjs/remark) and [rehype](https://github.com/rehypejs/rehype).

First, I just wanted to clarify that [actual top-level Docusaurus plugins](https://docusaurus.io/docs/advanced/plugins) (such as the `plugin-content-docs` plugin being used to generate this site) are distinct from `remark` / `rehype` plugins and the related ecosystem.

The `plugin-content-docs` plugin that is doing most of the heavy lifting for us uses [MDX](https://mdxjs.com/) (basically Markdown meets React's JSX) to parse the `.mdx` content files. As such, the `plugin-content-docs` plugin can optionally [be configured with some `remark` / `rehype` plugins](https://docusaurus.io/docs/markdown-features/plugins) that it passes directly to MDX.

Point being: there are ways to extend the functionality of Docusaurus that have nothing to do with `remark` / `rehype`.

That being said: if you want to add custom Markdown syntax (like we want to do with autocoloring) then a `remark` or `rehype` plugin is definitely the way to go, so this conversation is important.

My personal opinion would be to switch to ES6 modules and use the shim, if that's the only thing required to make everything else work. Have you verified whether that the sidebar config still resolves correctly?

My opinion is primarily motivated by this little note on [the page describing MDX plugin use](https://docusaurus.io/docs/markdown-features/plugins#installing-plugins):
> There's recently a trend in the Remark/Rehype ecosystem to migrate to ES Modules, a new JavaScript module system, which Docusaurus doesn't support yet. Please make sure your installed plugin version is CommonJS-compatible before we officially support ESM.

which suggests they intend to support it. If ES6 module support makes it into Docusaurus v3, then we've set ourselves up for success. I suspect we will almost definitely want to migrate once it's stable since Docusaurus v3 upgrades MDX to v2 which fixes a lot of quirks in MDX v1.

I don't like the idea of renaming the expected config file and having to update every current and potential future command in `package.json`. I'd rather just leave the shim with the conventional name and maybe leave a comment in it explaining the situation. Then we can call the "real" config whatever we like.

It's probably also worth it to explore other Docusaurus projects and see if/how they have solved this problem. It should be easy since they have [a showcase of Docusaurus projects](https://docusaurus.io/showcase) most of which probably link to their own source. I can definitely take a look at some over the coming days.

**Comment by seanmakesgames** [comment]
Agree with proposal. ES6 modules are also the syntax that Typescript uses.

Also agree with looking at how other docusaurus project solve it.

**Comment by ast-ral** [comment]
To @danswann: yes, thank for clarifying what exactly we'd be using it for. It's important to be clear what the relationship between these dependencies and Docusaurus is exactly.

After messing around with the problem more, I think the best solution is just to stick to CommonJS. We can work around the ESM-only dependencies within the bounds of CommonJS modules by making any file which imports ESM-only dependencies export an async function which resolves to what should be the _actual_ exports of the module. Instead of,
```js
module.exports = {x: /* */, y: /* */}
```
We would write:
```js
module.exports = async function () {
    // await imports here
    
    return {x: /* */, y: /* */};
}
```
within our CommonJS files.

Instead of importing these CommonJS files with `require("module")`, we'd have to import them with `await require("module")()`. We would likely want to have comments explaining why this is the case whenever it occurs. This kind of transformation is viral: any module that transitively imports an ESM module will also have to do this, so we will also have to modify `docusaurus.config.js` to export an async function that returns the config object. There is a slight hazard if these modules get imported with `await require("module")()` more than once: it will run any setup within the `async function` more than once as well. However, this problem is solvable by, for example, caching what should be exported and returning that at the start of the function if it's already been generated.

This solution isn't pretty or particularly good, but it works.

**Comment by danswann** [comment]
Yeah, after today's adventure I'd say the working CommonJS solution our best bet and that other solutions are generally not worth the investigative effort compared to how little we will probably end up modifying a lot of the plugin and other top-level code.

**Comment by seanmakesgames** [comment]
@ast-ral We'll probably be getting to this work soon-ish. Can you put together a branch with the scratch stuff that we had, that sorts this out with just the js? (we will lose some context if we don't capture it while it's fresh.)
Likely there's benefit to having TS for the plugin code, even if it doesn't solve the problem, but we can make that call after when we are thinking about modifications to color.js

**Comment by danswann** [comment]
After exploring a lot of packages that use Docusaurus for their doc sites, including well-known projects like [Jest](https://github.com/jestjs/jest/tree/main/website), [Redis](https://github.com/redis-developer/redis-developer.github.io/tree/master), [React Native](https://github.com/facebook/react-native-website/tree/main/website), and [Algolia DocSearch](https://github.com/algolia/docsearch/tree/main/packages/website), the conclusion is that while many use ES Modules (and sometimes TypeScript) for their custom React components and other browser-runtime utility code, nobody has attempted to use ES Modules and/or Typescript for their top level config code. The former is supported out of the box by Docusaurus, while the latter obviously isn't and is a non-trivial problem given the time we spent on it.

This is likely because for almost every project, the amount and complexity of "front-end code" they are writing vastly outweighs the amount of "build-time code." This will probably also eventually be true for us, as the amount of problems that are more easily solved by writing custom React components will be more numerous than the amount of problems that are more easily solved by using tools from the `unified` ecosystem to extend Markdown functionality. Short of autocoloring and wiki-style links, I don't see us needing to do any more in the MDX plugin space.

So if it's important for us to switch the (likely 2-5 when all is said and done) "build-time" files to ES Modules (with the exception of the shim) and/or use TypeScript for TypeScript's sake then we're in uncharted territories. We need to weigh the benefits (making one line of code slightly less ugly and/or supporting strong typing in a handful of additional files) against the cost of implementation.

My personal take is still that it's not worth the hassle when we already have a working solution and don't anticipate writing much more "build-time code."

**Comment by seanmakesgames** [comment]
Sounds like there was a miscommunication here. As I understand it, I don't think things work at all with our plugin, and my request is for us to capture the fix in js form. Maybe I'm misunderstanding?
Are you suggesting that we do something else here?

**Comment by danswann** [comment]
It works in the prototype repo, we were just forced us to use the `async module.exports = function(){}` and `await import() / await require()()` syntax explained in @ast-ral 's most recent comment because we were importing ES-only Modules (`unist-builder`, etc.) into [our CommonJS `color.js` module](https://github.com/DrizzlyBear/hackmud_wiki/blob/main/src/plugins/remark/color.js).

We could port that over line-for-line and it would work just as well here, with the same dynamic import syntax caveat.

This topic was originally brought up because we would like to be able to not have to do that (for example by using ES Module syntax in our own code), not because it didn't function.

**Comment by seanmakesgames** [comment]
Oh- well I thought that we didn't have the code you are mentioning-- which is all that I was asking for ast to write up in a branch, but we already have it.

As expected, we agree on everything. Closing the issue. :)
